AllCops:
  Exclude:
    - "db/schema.rb"
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
 Max: 30

Naming/VariableNumber:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 15