version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=production bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/chess_ranking
    depends_on:
      - db
    environment:
      RAILS_ENV: production
    healthcheck:
      test: "curl http://localhost:3000 || exit 1"
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s
  nginx:
    container_name: chess_ranking_nginx
    build: docker/nginx/
    volumes:
      - ./run/:/var/run/
    depends_on:
      web:
        condition: service_healthy
